---
title: "Readme"
author: "Alex Crest"
date: "2026-04-01"
output: html_document
---

Hello Everyone! This is the Readme File for the Comparing Sentiment Analysis Methods in R.

This workshop focused on how to start working with sentiment and introducing you to several tools.

Alex Crest and Aybuke Atalay developed and curated the material in this repo.

In this course, we are going to cover:

How to use and analyse sentiment
When to use which methods
Data processing
Summarising and interpreting results
Validating Results
Visualising with R



# Installing R and R Studio

## For R On Noteable
Go to https://noteable.edina.ac.uk/login
Login with your EASE credentials
Select RStudio as a personal notebook server and press start
Go to File > New Project> Version Control > Git
Copy and Paste this repository URL https://github.com/DCS-training/IntroToRAndRStudio as the Repository URL (The Project directory name will be filled in automatically but you can change it if you want your folder in Notable to have a different name).
Decide where to locate the folder. By default, it will locate it in your home directory
Press Create Project Congratulations you have now pulled the content of the repository on your Notable server space.

## Install it locally
If you have administrative rights of your laptop
Go to (https://www.r-project.org/)[https://www.r-project.org/]
Go to the download link
Choose your CRAN mirror nearer to your location (either Bristol or Imperial College London)
Download the correspondent version depending if you are using Windows Mac or Linux
For Windows click on install R for the first time. Then download R for Windows and follow the installation widget. If you get stuck follow this (video tutorial)[https://www.youtube.com/watch?v=GAGUDL-4aVw]
For Mac Download the most recent pkg file and follow the installation widget. If you get stuck follow this (video tutorial)[https://www.youtube.com/watch?v=EmZqlcKkJMM]
Once R is installed you can install R studio (R interface)
Go to (www.rstudio.com)[www.rstudio.com]
Go in download
Download the correspondent version depending on your Operating system and install it. If you get stuck check the videos linked above.


## If you have a UoE managed desktop
Go to the software centre (press the up arrow on the bottom bar of Windows and double-click on the Software Centre app)
Search for RStudio in the search bar
Install the R 4.4.1(with RStudio 2024.04.2) NB this will take quite some time so make sure to do it ahead of the first class

All material collected here is free to use but is covered by a License: License: CC BY-NC 4.0 license






